Repository umc-8th-Channeling/BE, pull requests merged in 2025-08, with the labels that each got.

#69 [FIX] TrendKeyword 외래키 report로 변경
  src/main/java/channeling/be/domain/TrendKeyword/domain/TrendKeyword.java
Labels: :bug: 버그

#70 [REFACTOR] : 커서기반-> 페이지네이션 변경
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
Labels: 🛠️ 리팩토링

#76 v0.0.9 회원 정보 조회, swagger 설정 완료 중간 배포
  .gitignore
  Dockerfile
  src/main/java/channeling/be/domain/TrendKeyword/domain/TrendKeyword.java
  src/main/java/channeling/be/domain/auth/application/MemberOauth2UserService.java
  src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
  src/main/java/channeling/be/domain/channel/application/ChannelService.java
  src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelSwagger.java
  src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
  src/main/java/channeling/be/domain/common/BaseEntity.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
  src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
  src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
  src/main/java/channeling/be/domain/memberAgree/application/MemberAgreeServiceImpl.java
  src/main/java/channeling/be/domain/memberAgree/domain/repository/MemberAgreeRepository.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeApi.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeController.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeReqDto.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/ExceptionAdvice.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🔖버전

#78 [FEAT]: 북마크한 아이디어 조회
  src/main/java/channeling/be/domain/idea/application/IdeaService.java
  src/main/java/channeling/be/domain/idea/application/IdeaServiceImpl.java
  src/main/java/channeling/be/domain/idea/domain/repository/IdeaRepository.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaConverter.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaResDto.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
Labels: :memo: 문서, :rainbow: 기능

#79 v0.1.0
  src/main/java/channeling/be/domain/idea/application/IdeaService.java
  src/main/java/channeling/be/domain/idea/application/IdeaServiceImpl.java
  src/main/java/channeling/be/domain/idea/domain/repository/IdeaRepository.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaConverter.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaResDto.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
Labels: 🔖버전

#81 [FIX] 컨테이너 종료 후 이미지 삭제하는 걸로 수정
  .github/workflows/CD.yml
Labels: :bug: 버그, :earth_americas: 인프라

#90 [FEAT]: 리포트의 댓글 카테고리별 조회
  src/main/java/channeling/be/domain/comment/domain/repository/CommentRepository.java
  src/main/java/channeling/be/domain/report/application/ReportService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/domain/repository/ReportRepository.java
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
  src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
  src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/handler/ReportHandler.java
Labels: :memo: 문서, :rainbow: 기능

#97 v1.0.0 Deploy
  src/main/java/channeling/be/domain/auth/application/MemberOauth2UserService.java
  src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
  src/main/java/channeling/be/domain/comment/domain/repository/CommentRepository.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/report/application/ReportService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/domain/repository/ReportRepository.java
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
  src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
  src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
  src/main/java/channeling/be/domain/task/domain/repository/TaskRepository.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/handler/ReportHandler.java
  src/main/java/channeling/be/response/exception/handler/TaskHandler.java
Labels: 🔖버전

#103 [FEAT] pr-review.yml 추가
  .github/workflows/pr-review.yml
Labels: :earth_americas: 인프라, :recycle: 테스트

#112 [FIX] logs 생성 시 UID 1000 권한으로 생성하게 수정
  Dockerfile
Labels: :bug: 버그, :earth_americas: 인프라

#117 [FEAT] 리포트 조회 메서드에 재시도 로직 추가
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
Labels: :bug: 버그

#121 [FIX] 트랜잭션 롤백 오류 해결
  src/main/java/channeling/be/domain/report/application/ReportDeleteService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
Labels: :bug: 버그

#122 v1.0.4 리포트 생성 트랜잭션 오류 해결
  src/main/java/channeling/be/domain/report/application/ReportDeleteService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
Labels: :bug: 버그, :earth_americas: 인프라

#126 v1.0.6 로그 디렉토리 권한 부여
  .github/workflows/CD.yml
Labels: :earth_americas: 인프라

#109 [FEAT]: 리포트 삭제
  src/main/java/channeling/be/domain/report/application/ReportService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
  src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
Labels: :rainbow: 기능

#127 [CHORE]: 요청 uri restful 하게 수정 + 상태 조회 리포트로 조회하도록 수정
  build.gradle
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelSwagger.java
  src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaController.java
  src/main/java/channeling/be/domain/idea/presentation/IdeaSwagger.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
  src/main/java/channeling/be/domain/member/presentation/MemberSwagger.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeApi.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeController.java
  src/main/java/channeling/be/domain/memberAgree/presentation/MemberAgreeReqDto.java
  src/main/java/channeling/be/domain/report/application/ReportService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/report/presentation/ReportConverter.java
  src/main/java/channeling/be/domain/report/presentation/ReportResDto.java
  src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
Labels: 🛠️ 리팩토링

#129 [FEAT]: URL로 리포트 생성 요청
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/report/presentation/ReportReqDto.java
  src/main/java/channeling/be/domain/report/presentation/ReportSwagger.java
  src/main/java/channeling/be/domain/video/application/VideoService.java
  src/main/java/channeling/be/domain/video/application/VideoServiceImpl.java
  src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/ExceptionAdvice.java
Labels: :memo: 문서, :rainbow: 기능

#139 v1.1.3 멤버 조회 결과에 동의 여부 추가
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
  src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
Labels: 🔖버전

#144 [FEAT] CORS 허용 추가
  src/main/java/channeling/be/global/config/SecurityConfig.java
Labels: :bug: 버그, :earth_americas: 인프라

#150 [HOTFIX] 채널의 리포트 리스트 조회 결과에 채널명 추가
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/presentation/dto/ReportResDTO.java
Labels: 🛠️ 리팩토링

#153 v1.1.8 채널 리포트 리스트 조회에 videoId 추가
  src/main/java/channeling/be/domain/report/presentation/dto/ReportResDTO.java
Labels: :earth_americas: 인프라

#166 v 1.2.1 api path /v2로 변경
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
Labels: :earth_americas: 인프라
