Repository umc-8th-Channeling/BE, pull requests merged in 2025-07, with the labels that each got.

#12 [FEAT] 프로젝트 기본 세팅
  .github/pull_request_template.md
  .gitignore
  build.gradle
  src/main/java/channeling/be/BeApplication.java
  src/main/java/channeling/be/domain/TrendKeyword/domain/TrendKeyword.java
  src/main/java/channeling/be/domain/TrendKeyword/domain/TrendKeywordType.java
  src/main/java/channeling/be/domain/TrendKeyword/domain/repository/TrendKeywordRepository.java
  src/main/java/channeling/be/domain/channel/application/ChannelService.java
  src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
  src/main/java/channeling/be/domain/channel/domain/Channel.java
  src/main/java/channeling/be/domain/channel/domain/ChannelHashTag.java
  src/main/java/channeling/be/domain/channel/domain/repository/ChannelRepository.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/comment/domain/Comment.java
  src/main/java/channeling/be/domain/comment/domain/CommentType.java
  src/main/java/channeling/be/domain/comment/domain/repository/CommentRepository.java
  src/main/java/channeling/be/domain/common/BaseEntity.java
  src/main/java/channeling/be/domain/idea/domain/Idea.java
  src/main/java/channeling/be/domain/idea/domain/repository/IdeaRepository.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/domain/Member.java
  src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/memberAgree/domain/MemberAgree.java
  src/main/java/channeling/be/domain/memberAgree/domain/repository/MemberAgreeRepository.java
  src/main/java/channeling/be/domain/report/application/ReportService.java
  src/main/java/channeling/be/domain/report/application/ReportServiceImpl.java
  src/main/java/channeling/be/domain/report/domain/Report.java
  src/main/java/channeling/be/domain/report/domain/repository/ReportRepository.java
  src/main/java/channeling/be/domain/report/presentation/ReportController.java
  src/main/java/channeling/be/domain/video/application/VideoService.java
  src/main/java/channeling/be/domain/video/application/VideoServiceImpl.java
  src/main/java/channeling/be/domain/video/domain/Video.java
  src/main/java/channeling/be/domain/video/domain/VideoCategory.java
  src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
  src/main/java/channeling/be/domain/video/presentaion/VideoController.java
  src/main/java/channeling/be/global/config/QueryDSLConfig.java
  src/main/java/channeling/be/response/code/BaseCode.java
  src/main/java/channeling/be/response/code/BaseErrorCode.java
  src/main/java/channeling/be/response/code/ErrorReasonDTO.java
  src/main/java/channeling/be/response/code/ReasonDTO.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/code/status/SuccessStatus.java
  src/main/java/channeling/be/response/exception/ExceptionAdvice.java
  src/main/java/channeling/be/response/exception/GeneralException.java
  src/main/java/channeling/be/response/exception/handler/ApiResponse.java
  src/main/java/channeling/be/response/exception/handler/MemberHandler.java
Labels: :earth_americas: 인프라, :rainbow: 기능

#18 [FEAT] 배포 방식 docker-compose 방식으로 변경
  .github/workflows/CD.yml
  Dockerfile
  build.gradle
Labels: :earth_americas: 인프라

#15 [FEAT]: 채널 컨셉 수정
  src/main/java/channeling/be/domain/channel/application/ChannelService.java
  src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
  src/main/java/channeling/be/domain/channel/domain/Channel.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
  src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
  src/main/java/channeling/be/domain/channel/presentation/dto/response/ChannelResponseDto.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
Labels: :rainbow: 기능

#24 [FEAT]: 채널 타겟 층 수정 구현 완료 + 채널 컨셉 수정 리펙토링
  src/main/java/channeling/be/domain/channel/application/ChannelService.java
  src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
  src/main/java/channeling/be/domain/channel/domain/Channel.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/channel/presentation/ChannelConverter.java
  src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
  src/main/java/channeling/be/domain/channel/presentation/dto/request/ChannelRequestDto.java
  src/main/java/channeling/be/domain/channel/presentation/dto/response/ChannelResponseDto.java
Labels: :rainbow: 기능, 🛠️ 리팩토링

#31 [FEAT] 회원 SNS 링크 업데이트
  src/main/java/channeling/be/domain/channel/presentation/ChannelController.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/domain/Member.java
  src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
  src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
  src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/code/status/SuccessStatus.java
  src/main/java/channeling/be/response/exception/handler/MemberHandler.java
Labels: :bug: 버그, :rainbow: 기능

#33 [FEAT]: 자체 인증 구현 (Spring Security, JWT, Redis)
  build.gradle
  src/main/java/channeling/be/domain/auth/annotation/LoginMember.java
  src/main/java/channeling/be/domain/auth/annotation/LoginMemberArgumentResolver.java
  src/main/java/channeling/be/domain/auth/application/CustomUserDetailsService.java
  src/main/java/channeling/be/domain/auth/application/MemberOauth2UserService.java
  src/main/java/channeling/be/domain/auth/domain/CustomUserDetails.java
  src/main/java/channeling/be/domain/auth/filter/AuthenticationEntryPointImpl.java
  src/main/java/channeling/be/domain/auth/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/global/config/RedisConfig.java
  src/main/java/channeling/be/global/config/SecurityConfig.java
  src/main/java/channeling/be/global/infrastructure/jwt/JwtUtil.java
  src/main/java/channeling/be/global/infrastructure/jwt/JwtUtilImpl.java
  src/main/java/channeling/be/global/infrastructure/redis/RedisUtil.java
  src/main/java/channeling/be/global/resolver/WebMvcConfig.java
  src/main/resources/application-jwt.yml
Labels: :rainbow: 기능

#37 [CHORE] report 테이블 video_id 제외한 칼럼들 nullable
  src/main/java/channeling/be/domain/report/domain/Report.java
Labels: :bug: 버그

#41 [FEAT]: 멤버 이미지 수정 (S3 도입)
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/member/domain/Member.java
  src/main/java/channeling/be/domain/member/domain/repository/MemberRepository.java
  src/main/java/channeling/be/domain/member/presentation/MemberController.java
  src/main/java/channeling/be/domain/member/presentation/MemberConverter.java
  src/main/java/channeling/be/domain/member/presentation/MemberReqDTO.java
  src/main/java/channeling/be/domain/member/presentation/MemberResDTO.java
  src/main/java/channeling/be/global/config/S3Config.java
  src/main/java/channeling/be/global/infrastructure/aws/S3Service.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/handler/S3Handler.java
  src/main/resources/application-s3.yml
Labels: :rainbow: 기능

#43 [FEAT] : 유튜브 API 기반 로그인 사용자 정보 풀링 기능 구현
  src/main/java/channeling/be/domain/auth/application/MemberOauth2UserService.java
  src/main/java/channeling/be/domain/auth/handler/Oauth2LoginSuccessHandler.java
  src/main/java/channeling/be/domain/channel/application/ChannelService.java
  src/main/java/channeling/be/domain/channel/application/ChannelServiceImpl.java
  src/main/java/channeling/be/domain/channel/application/model/Stats.java
  src/main/java/channeling/be/domain/channel/domain/Channel.java
  src/main/java/channeling/be/domain/channel/domain/repository/ChannelRepository.java
  src/main/java/channeling/be/domain/channel/presentation/converter/ChannelConverter.java
  src/main/java/channeling/be/domain/member/application/MemberService.java
  src/main/java/channeling/be/domain/member/application/MemberServiceImpl.java
  src/main/java/channeling/be/domain/video/application/VideoService.java
  src/main/java/channeling/be/domain/video/application/VideoServiceImpl.java
  src/main/java/channeling/be/domain/video/domain/Video.java
  src/main/java/channeling/be/domain/video/domain/VideoConverter.java
  src/main/java/channeling/be/domain/video/domain/repository/VideoRepository.java
  src/main/java/channeling/be/global/infrastructure/youtube/YoutubeUtil.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/model/YoutubeVideoBriefDTO.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/model/YoutubeVideoDetailDTO.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/model/YoutubeVideoListResDTO.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/res/YoutubeAnalyticsResDTO.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/res/YoutubeChannelResDTO.java
  src/main/java/channeling/be/global/infrastructure/youtube/dto/res/YoutubePlayListResDTO.java
  src/main/java/channeling/be/response/code/status/ErrorStatus.java
  src/main/java/channeling/be/response/exception/handler/YoutubeHandler.java
Labels: :rainbow: 기능

#50 [CHORE] Task 테이블 Enum 타입 칼럼에 String값 허용
  src/main/java/channeling/be/domain/task/domain/Task.java
Labels: :bug: 버그, :rainbow: 기능

#52 [BUILD] 구글 로그인, jwt 관련 환경 변수 추가
  .github/workflows/CD.yml
Labels: :earth_americas: 인프라

#57 [Build] Redis 호스트 주소 환경 변수로 변경 + 배포 시 이전 Docker 이미지 삭제 step 추가 (#56)
  .github/workflows/CD.yml
  src/main/resources/application-db.yml
Labels: :bug: 버그, :earth_americas: 인프라
